### dev

POST  https://ldqzgmh4kh.execute-api.us-east-1.amazonaws.com/dev/token
Content-Type: application/x-www-form-urlencoded

clientId=42ir5sgjevt2ekdvr1g4st9me3
&poolId=us-east-1_5jQpJgMno
&username=veliti
&password=velitipass

### prod

POST https://cnnws06f96.execute-api.us-east-1.amazonaws.com/prd/token
Content-Type: application/x-www-form-urlencoded

clientId=42ir5sgjevt2ekdvr1g4st9me3
&poolId=us-east-1_5jQpJgMno
&username=veliti
&password=velitipass*****EEEERRRROOOO
