POST https://ux7jpfn07f.execute-api.us-east-1.amazonaws.com/dev/v1/token

{
	"clientId": "4icqdo0ia8ifbvmfpv0ptgt9s1",
	"poolId": "us-east-1_YYTAAxPEa",
	"username": "veliti",
	"password": "velitipass"
}